name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: compile
        run: g++ -o TinyLoad.exe TinyLoad.cpp -static -O2 -s
